'use strict';
(() => {
  const api=window.eaglePlayground;
  if(!api)return;
  const $=s=>document.querySelector(s);
  const $$=s=>[...document.querySelectorAll(s)];
  const escapeHTML=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let shot=0,adPlaying=false,adTimer=null,adStarted=false,adFinished=false,activeAgent='stath',truthShown=false,musicTimer=null,musicBeat=0;
  const shots=[
    {kicker:'STATH & AL PRESENT',heading:'MICHAEL\n& EAGLE.',sub:'A company with people in.',director:'Al, has it started?',image:'assets/studio.webp',alt:'A studio flat in the company presentation',take:'TAKE 04'},
    {kicker:'RESIDENTIAL LETTINGS',heading:'A LOVELY\nINSIDE.',sub:'We can take you directly to the rooms.',director:'That’s it. Get all of the inside in.',image:'assets/studio.webp',alt:'The studio flat, with a bed next to the kitchen',take:'TAKE 04'},
    {kicker:'OUR PEOPLE',heading:'RESPECT.',sub:'Absolutely coming off them.',director:'Al, yours is coming off you as well.',image:'assets/studio.webp',alt:'',take:'TAKE 06'},
    {kicker:'ATTENTION TO DETAIL',heading:'HOWLEY\nPARKER!',sub:'An exceptionally close relationship with property.',director:'That’s the zoom. Al, come back a little bit.',image:'assets/loft.webp',alt:'An unexpectedly close view of the attic flat',take:'TAKE 06'},
    {kicker:'VIEWINGS BY APPOINTMENT',heading:'ALL THE FUN\nOF THE FAIR.',sub:'Sophie has brought something to the presentation.',director:'Keep filming. This is showing the atmosphere.',image:'assets/studio.webp',alt:'The studio flat and its disco ball',take:'TAKE 07'},
    {kicker:'IN RECOGNITION OF EXCELLENCE',heading:'AWARD\nWINNING.',sub:'The Silly Billy Awards.',director:'We can keep that one in. It’s still an award.',image:'assets/studio.webp',alt:'',take:'TAKE 07'},
    {kicker:'YOUR LOCAL PROPERTY PROFESSIONALS',heading:'MICHAEL\n& EAGLE.',sub:'Perfect to meet you.',director:'Have you stopped it, Al? Al?',image:'assets/studio.webp',alt:'',take:'FINAL_FINAL'}
  ];
  const awards=new Map([
    ['stath-keys',{name:'Stath',title:'Excellence in Key Selection',reason:'For arriving at a viewing with the key to his own flat.'}],
    ['al-gentleman',{name:'Al',title:'Most Considerate Gentleman',reason:'For politely moving out of everyone’s way, including his own.'}],
    ['sophie-movement',{name:'Sophie',title:'Services to Additional Movements',reason:'For bringing a dance to an ordinary business occasion.'}]
  ]);
  function updateAwards(){const items=[...awards.values()];const latest=items[items.length-1];$('#current-winner').textContent=latest.name;$('#current-reason').textContent=latest.reason;$('#award-log').replaceChildren();items.slice(-4).reverse().forEach((award,i)=>{const li=document.createElement('li'),number=document.createElement('span'),text=document.createElement('div'),b=document.createElement('b'),small=document.createElement('small');number.textContent=String(items.length-i).padStart(2,'0');b.textContent=award.title;small.textContent=`${award.name} · ${award.reason}`;text.append(b,small);li.append(number,text);$('#award-log').append(li)});$('#award-cabinet').textContent=`Inspect all ${awards.size} certificates`}
  function award(id,reason,name='The visitor',title='A Silly Billy Award'){if(awards.has(id))return false;awards.set(id,{reason,name,title});updateAwards();const board=$('.honours-board');board.classList.remove('award-arrived');void board.offsetWidth;board.classList.add('award-arrived');api.toast(`Silly Billy Awards · ${title}. Very strong work, ${name}.`);api.beep(587,.12);return true}
  function renderShot(index,{performance=false}={}){shot=Math.max(0,Math.min(shots.length-1,index));const scene=shots[shot];$('#ad-screen').dataset.shot=String(shot);$('#ad-image').src=scene.image;$('#ad-image').alt=scene.alt;$('#ad-kicker').textContent=scene.kicker;$('#ad-heading').textContent=scene.heading;$('#ad-subtitle').textContent=scene.sub;$('#ad-director').textContent=scene.director;$('#ad-take').textContent=scene.take;$('#ad-counter').textContent=`${String(shot+1).padStart(2,'0')} / 07`;$('#ad-progress').style.width=`${(shot+1)/shots.length*100}%`;if(shot===4&&performance&&api.getSettings().motion){window.eagleCrump?.play('shuffle');$('#crump-status').textContent='Sophie is demonstrating the atmosphere. Al is still filming.'}return {shot:shot+1,title:scene.heading.replace('\n',' ')}}
  function filmMusic(){clearTimeout(musicTimer);if(!adPlaying||document.hidden)return;const melody=[523.25,659.25,783.99,659.25,587.33,698.46,880,0,659.25,783.99,1046.5,783.99,698.46,587.33,523.25,0];const note=melody[musicBeat++%melody.length];if(api.getSettings().sound&&note)api.beep(note,.22,.045);musicTimer=setTimeout(filmMusic,350)}
  function pauseAd({quiet=false}={}){clearTimeout(musicTimer);musicTimer=null;clearTimeout(adTimer);adTimer=null;adPlaying=false;$('#ad-screen').classList.remove('ad-is-playing');$('#ad-play').textContent=adFinished?'Play again':adStarted?'Resume presentation':'Play presentation';window.eagleCrump?.stop({quiet:true});if(!quiet&&adStarted&&!adFinished)$('#crump-status').textContent='Paused. Stath would like that pause cut out.'}
  function finishAd(){pauseAd({quiet:true});adFinished=true;$('#ad-play').textContent='Play again';$('#crump-status').textContent='Thank you for watching. Al, it’s still recording.';award('film','For staying through all seven shots of the company presentation.','The visitor','Outstanding Commitment to Corporate Cinema')}
  function queueShot(){clearTimeout(adTimer);if(!adPlaying)return;adTimer=setTimeout(()=>{if(shot===shots.length-1)finishAd();else{renderShot(shot+1,{performance:true});queueShot()}},3500)}
  function playAd(){if(adPlaying){pauseAd();return {playing:false}}if(adFinished){shot=0;adFinished=false}adStarted=true;adPlaying=true;$('#ad-screen').classList.add('ad-has-started','ad-is-playing');$('#ad-play-overlay').hidden=true;$('#ad-play').textContent='Pause presentation';$('#crump-status').textContent='Company presentation. Stath has asked that we all watch it.';renderShot(shot,{performance:false});api.beep(440,.08);musicBeat=shot*10;filmMusic();queueShot();return {playing:true,shot:shot+1}}
  function resetAd(){pauseAd({quiet:true});adStarted=false;adFinished=false;$('#ad-screen').classList.remove('ad-has-started');$('#ad-play-overlay').hidden=false;$('#ad-play').textContent='Play presentation';renderShot(0);$('#ad-progress').style.width='0%'}
  $('#ad-play').addEventListener('click',playAd);$('#ad-play-overlay').addEventListener('click',playAd);$('#ad-next').addEventListener('click',()=>{clearTimeout(adTimer);if(shot===shots.length-1){finishAd();return}adStarted=true;$('#ad-screen').classList.add('ad-has-started');$('#ad-play-overlay').hidden=true;renderShot(shot+1,{performance:true});if(adPlaying)queueShot();else $('#ad-play').textContent='Resume presentation'});
  const profiles={
    stath:{caption:'Stath · Lettings & introductions',action:'Read Stath’s references',respect:48,reference:'A very active member of the business. Has personally touched nearly every key.'},
    al:{caption:'Al · Mayor of Gentleman Town',action:'Check Al’s official standing',respect:96,reference:'Respect absolutely coming off him. Very calm with a folder. A gentleman of the highest available calibre.'},
    sophie:{caption:'Sophie · Only helping for a little bit',action:'Check Sophie’s availability',respect:76,reference:'Available for a viewing. Also available for a movement during the viewing. They may coincide.'},
    carole:{caption:'Carole · Property details, correctly',action:'Ask Carole to check the details',respect:90,reference:'Can provide a floor area without comparing it to a member of staff. This is a significant qualification.'},
    cem:{caption:'Cem · Visiting gentleman',action:'Request a professional reference',respect:99,reference:'There’s respect absolutely coming off you. You’ve read this reference respectfully. I respect that as well.'},
    vasos:{caption:'Vasos · Family business',action:'Read Dad’s recommendation',respect:93,reference:'Stath is my wonderful boy. Sophie is my wonderful girl. And Al is a wonderful Al. You can put that on the website.'},
    dean:{caption:'Dean · Present for contractual reasons',action:'Ask Dean for a recommendation',respect:61,reference:'The flat is on the website. If you like it, look at it. I don’t think we need to keep giving each other certificates.'},
    eagle:{caption:'The eagle · Local coverage',action:'Check coverage',respect:12,reference:'[A property is carried past the window. The reference is considered complete.]'}
  };
  function syncProfile(agent){activeAgent=agent;const p=profiles[agent];$('#staff-caption').textContent=p.caption;$('#staff-action').textContent=p.action;$('#respect-fill').style.width=`${p.respect}%`;$('#respect-value').textContent=p.respect>=100?'Absolutely coming off them':p.respect>=90?'Exceptional':p.respect>=60?'Very respectable':'Developing nicely'}
  function certificate({kind='award',name='The visitor',reason='For a very strong showing, actually.'}={}){const civic=kind==='mayor';const safeName=escapeHTML(name);api.showDialog(`<div class="dialog-content"><div class="certificate-sheet"><p class="certificate-small">${civic?'GENTLEMAN TOWN · OFFICE OF THE MAYOR':'MICHAEL & EAGLE · RECOGNITION OF ACHIEVEMENT'}</p><h2 id="dialog-title">${civic?'MAYOR OF<br>GENTLEMAN TOWN.':'THE SILLY<br>BILLY AWARDS.'}</h2><p class="certificate-small">HEREBY PRESENTED TO</p><div class="certificate-name">${safeName}</div><p class="certificate-why">${escapeHTML(reason)}</p><div class="award-signature">Stath <span>${civic?'Returning Officer, very respectful':'Head Judge & Previous Winner'}</span></div><p class="certificate-footer">${civic?'Respect absolutely coming off this appointment.':'The committee has been both unanimous and Stath.'}</p></div><button class="button blue" id="certificate-accept">Accept with dignity</button></div>`,'certificate');$('#certificate-accept').addEventListener('click',()=>{api.closeDialog();api.toast(civic?'A very respectful inauguration. The town is in excellent hands.':'Silly Billy Awards. A lovely honour to have indoors.');api.rain('✳',13)});return {kind,name}}
  function standards(){api.showDialog('<div class="dialog-content"><p class="eyebrow">OUR PROFESSIONAL STANDARDS</p><h2 id="dialog-title">BUILT ON<br>RESPECT.</h2><ol class="standards-list"><li>Respect for the customer.</li><li>Respect for the property.</li><li>Respect for Al, who is holding the property details.</li><li>A respectful additional amount, if required.</li></ol><p>We feel you have approached this document in a very gentlemanly way.</p><button class="button blue" id="accept-standards">Acknowledge the standards</button></div>','standards');$('#accept-standards').addEventListener('click',()=>{award('mayor','For approaching the company standards with exceptional respect.','The visitor','Civic Services to Gentleman Town');certificate({kind:'mayor',name:'The visitor',reason:'For reading all four standards and conducting yourself like a very good gentleman.'})})}
  function reference(){const p=profiles[activeAgent];if(activeAgent==='al'){certificate({kind:'mayor',name:'Al',reason:'For having respect absolutely coming off him, in all professional directions.'});return}if(activeAgent==='sophie'){pauseAd({quiet:true});window.eagleCrump?.play('shuffle');award('sophie-available','For scheduling a dance in an ordinary lettings appointment.','Sophie','Outstandingly Flexible Availability');return}if(activeAgent==='carole'){pauseAd({quiet:true});api.setTranslation(true);window.eagleCrump?.stop({rescue:true,quiet:true});$('#office-reply').textContent='“There. I’ve checked the details and stopped the presentation. We can all do some work.”';return}if(activeAgent==='eagle'){api.unleashEagle();return}const name={stath:'Stath',cem:'Cem',vasos:'Vasos',dean:'Dean'}[activeAgent];api.showDialog(`<div class="dialog-content"><p class="eyebrow">PROFESSIONAL REFERENCE</p><h2 id="dialog-title">${escapeHTML(name.toUpperCase())}<br>RECOMMENDS.</h2><p class="reference-quote">${escapeHTML(p.reference)}</p><p class="dialog-fine">Reference supplied by the person currently being asked.</p><button class="button blue" id="reference-accept">Thank you. Very respectful.</button></div>`,'reference');$('#reference-accept').addEventListener('click',()=>{api.closeDialog();p.respect=Math.min(100,p.respect+10);syncProfile(activeAgent);if(activeAgent==='cem')certificate({kind:'mayor',name:'The visitor',reason:'Nominated by Cem for a quite exceptional amount of respect.'});else if(activeAgent==='stath')award('stath-reference','For supplying his own excellent reference.','Stath','Independent Self-Recommendation')})}
  $('#company-standards').addEventListener('click',standards);$('#staff-action').addEventListener('click',reference);
  function nominations(){api.showDialog('<div class="dialog-content"><p class="eyebrow">THE SILLY BILLY AWARDS</p><h2 id="dialog-title">A LOVELY<br>NOMINATION.</h2><p>The committee is delighted to receive a name. It has already found a certificate.</p><form class="nomination-form" id="nomination-form"><label>Name on the certificate<input id="nominee-name" name="name" value="Stath" maxlength="45" required autocomplete="off"></label><label>Outstanding achievement<select id="nominee-reason" name="reason"><option value="keys">A brave choice of entirely wrong key</option><option value="confidence">Exceptional confidence before checking anything</option><option value="movement">Additional movement during office hours</option><option value="gentleman">Services to Gentleman Town</option></select></label><button class="button blue" type="submit">Announce the winner</button></form></div>','nominations');$('#nomination-form').addEventListener('submit',e=>{e.preventDefault();const name=$('#nominee-name').value.trim().slice(0,45);if(!name){$('#nominee-name').focus();return}const category=$('#nominee-reason').value;const reasons={keys:'For a brave choice of entirely wrong key.',confidence:'For exceptional confidence before checking a single detail.',movement:'For bringing additional movement to an ordinary day at the office.',gentleman:'For having respect absolutely coming off you. The town would like to make that official.'};award(`nominee:${name}:${category}`,reasons[category],name,category==='gentleman'?'Services to Gentleman Town':'A Very Strong Silly Billy');certificate({kind:category==='gentleman'?'mayor':'award',name,reason:reasons[category]});$('#certificate-accept').focus()})}
  function cabinet(){const list=[...awards.values()].reverse().map(a=>`<li><b>${escapeHTML(a.title)}</b>${escapeHTML(a.name)} · ${escapeHTML(a.reason)}</li>`).join('');api.showDialog(`<div class="dialog-content"><p class="eyebrow">COMPANY HONOURS</p><h2 id="dialog-title">A VERY<br>GOOD SHELF.</h2><ul class="agency-award-list">${list}</ul><button class="button blue" id="another-nomination">Submit another nomination</button></div>`,'cabinet');$('#another-nomination').addEventListener('click',nominations)}
  $('#open-nominations').addEventListener('click',nominations);$('#award-cabinet').addEventListener('click',cabinet);
  document.addEventListener('eagle:award',e=>{if(e.detail?.id&&e.detail?.reason)award(e.detail.id,e.detail.reason)});
  document.addEventListener('eagle:agent',e=>{if(profiles[e.detail?.agent])syncProfile(e.detail.agent)});
  document.addEventListener('eagle:answer',e=>{const p=profiles[e.detail?.agent];if(!p)return;p.respect=Math.min(100,p.respect+4);syncProfile(e.detail.agent);if(p.respect===100&&e.detail.agent!=='carole')award(`respect:${e.detail.agent}`,'For conducting business with respect coming off in every direction.',{stath:'Stath',al:'Al',sophie:'Sophie',cem:'Cem',vasos:'Vasos',dean:'Dean',eagle:'The eagle'}[e.detail.agent],'Professional Respect, Absolutely')});
  document.addEventListener('eagle:translation',e=>{if(e.detail.enabled)truthShown=true;else if(truthShown)award('truth','For reading the actual details and returning confidently to the original description.','The visitor','Optimism Despite the Evidence')});
  document.addEventListener('eagle:restore',resetAd);
  document.addEventListener('eagle:preferences',()=>{if(!api.getSettings().motion)pauseAd({quiet:true})});
  document.addEventListener('visibilitychange',()=>{if(document.hidden)pauseAd({quiet:true})});
  window.addEventListener('pagehide',()=>pauseAd({quiet:true}));
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&adPlaying)pauseAd({quiet:true})});
  if('IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>{if(!entries[0].isIntersecting&&adPlaying)pauseAd({quiet:true})},{threshold:0});observer.observe($('#ad-screen'));window.addEventListener('pagehide',()=>observer.disconnect(),{once:true})}
  updateAwards();syncProfile('stath');
  window.eagleAgency={playAd,pauseAd,resetAd,renderShot,award,getState:()=>({shot:shot+1,adPlaying,adStarted,adFinished,awardCount:awards.size,activeAgent})};
})();
