'use strict';
(() => {
  const $ = s => document.querySelector(s);
  const $$ = s => [...document.querySelectorAll(s)];
  const properties = window.eagleProperties;
  const state={filter:'all',honest:false,property:'studio',inspected:new Set(),agent:'stath',question:null,chaos:80,sound:false,motion:!matchMedia('(prefers-reduced-motion: reduce)').matches};
  let toastTimer,flightTimer,holdTimer,audioContext,held=false,flightRunning=false,lastFocus;
  let dialogView=null;
  function money(n){return new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',maximumFractionDigits:0}).format(n)}
  function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),4500)}
  function withAudio(play){if(!state.sound||document.hidden)return;try{audioContext??=new(window.AudioContext||window.webkitAudioContext)();const run=()=>{if(state.sound&&!document.hidden)play(audioContext)};if(audioContext.state==='running')run();else Promise.resolve(audioContext.resume()).then(run).catch(()=>{state.sound=false;updatePreferences();toast('The sound hasn’t come through. Try Sound on once more.')})}catch{state.sound=false;updatePreferences()}}
  function beep(frequency=500,duration=.1,level=.055){withAudio(ctx=>{const t=ctx.currentTime,o=ctx.createOscillator(),g=ctx.createGain();o.type='sine';o.frequency.value=frequency;g.gain.setValueAtTime(.0001,t);g.gain.linearRampToValueAtTime(level,t+.008);g.gain.exponentialRampToValueAtTime(.001,t+duration);o.connect(g);g.connect(ctx.destination);o.onended=()=>{o.disconnect();g.disconnect()};o.start(t);o.stop(t+duration)})}
  function propertyPhoto(image,p,status){if(window.eagleImages)return window.eagleImages.show(image,p,status);image.src=p.image;image.alt=p.alt;return Promise.resolve(true)}
  function nextEagleQuip(){return window.eagleQuips.next()}

  function rain(symbol='✳',count=30){if(!state.motion)return;const layer=$('#confetti-layer');for(let i=0;i<count;i++){const p=document.createElement('span');p.className='particle';p.textContent=symbol;p.style.cssText=`--left:${Math.random()*100}%;--size:${18+Math.random()*20}px;--duration:${1.6+Math.random()*1.8}s;--delay:${Math.random()*.45}s;--drift:${Math.random()*240-120}px;--rotate:${Math.random()*700-350}deg;color:${['#2348ed','#e44b32','#ffe436'][i%3]}`;layer.append(p);p.addEventListener('animationend',()=>p.remove(),{once:true});setTimeout(()=>p.remove(),4500)}}
  function unleashEagle(){if(flightRunning)return;const quip=nextEagleQuip();toast(quip);$('#eagle-quip').textContent=quip;const report=$('#coverage-reply');if(report)report.textContent=quip;beep(880,.16);setTimeout(()=>beep(520,.25),180);if(!state.motion)return;flightRunning=true;$('#eagle-flight').classList.add('flying');rain('✳',20);clearTimeout(flightTimer);flightTimer=setTimeout(()=>{$('#eagle-flight').classList.remove('flying');flightRunning=false},3900)}
  function coverageReport(){const quip=nextEagleQuip();$('#coverage-reply').textContent=quip;beep(660,.18);const bird=$('#coverage-bird');if(state.motion){bird.classList.remove('surveying');void bird.offsetWidth;bird.classList.add('surveying')}}
  function openCoverage(){showDialog(`<div class="dialog-content eagle-report"><p class="eyebrow">LOCAL AREA: WE GO OVER IT</p><h2 id="dialog-title">A VERY WIDE<br>NEARBY.</h2><img class="coverage-bird" id="coverage-bird" src="assets/large/eagle.png" alt="Our area manager carrying a house"><p id="coverage-reply" class="coverage-reply" aria-live="polite"></p><div class="coverage-places"><p><b>Near the shops</b><span>A good walking distance, if you start from near them.</span></p><p><b>Above the shops</b><span>The same amenities. A more vertical approach.</span></p><p><b>Where Al has parked</b><span>Al says five minutes. We’re allowing for his apologising.</span></p></div><button class="button blue" id="coverage-flight">Ask for another area report</button><button class="text-button" id="coverage-flats">Let’s see the actual insides</button></div>`,'coverage');$('#coverage-flight').addEventListener('click',coverageReport);$('#coverage-flats').addEventListener('click',()=>{closeDialog();setFilter('all');$('#flats').scrollIntoView({behavior:state.motion?'smooth':'instant'})});coverageReport()}

  function matchesFilter(p,filter=state.filter){return filter==='all'||(filter==='new'&&p.newListing)||(filter==='budget'&&p.price<1500)||(filter==='airborne'&&p.id==='eagle')}
  function setFilter(filter){if(!['all','new','budget','airborne'].includes(filter))throw new Error('Unknown property filter');state.filter=filter;$$('[data-filter]').forEach(b=>{const on=b.dataset.filter===filter;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on))});let count=0;$$('.property-card').forEach(card=>{const p=properties.find(p=>p.id===card.dataset.id);const show=matchesFilter(p);card.hidden=!show;if(show)count++});$('#result-count').textContent=`${count} ${count===1?'property':'properties'} inside the computer`;return {filter,count}}
  function renderCards(){const focusId=document.activeElement?.dataset?.open;$('#property-grid').innerHTML=properties.map((p,i)=>`<article class="property-card" data-id="${p.id}"><div class="card-image ${p.id==='eagle'?'sky':''}"><img src="${p.image}" alt="${p.alt}" width="${p.newListing?1000:1536}" height="${p.newListing?667:1024}" loading="lazy" decoding="async"><span class="card-tag">${state.honest?p.honestTag:p.tag}</span><span class="card-number">M&E / ${String(i+1).padStart(3,'0')}</span></div><div class="card-content"><p class="location">${p.location}</p><h3>${state.honest?p.honestTitle:p.title}</h3><p class="property-copy">${state.honest?p.honest:p.pitch}</p><div class="card-specs"><span>${p.beds}</span><span>·</span><span>${p.feature}</span></div><div class="card-bottom"><span class="price">${money(p.price)} <small>/ month</small></span><button class="view-button" data-open="${p.id}" aria-label="View ${p.title}">Have a look</button></div>${p.photoNote?`<p class="photo-comment">${p.photoNote}</p>`:''}</div></article>`).join('');$$('[data-open]').forEach(b=>b.addEventListener('click',()=>openProperty(b.dataset.open)));setFilter(state.filter);if(focusId)$(`[data-open="${focusId}"]`)?.focus()}
  function setTranslation(enabled){if(typeof enabled!=='boolean')throw new Error('enabled must be a boolean');state.honest=enabled;$('#translator').setAttribute('aria-pressed',String(enabled));$('#translator-title').textContent=enabled?'Carole’s translation: on':'Translate agent-speak';$('#translator-sub').textContent=enabled?'There. Much more accurate.':'Let Carole tell you the truth.';renderCards();document.dispatchEvent(new CustomEvent('eagle:translation',{detail:{enabled}}));return {translation:enabled}}
  function showDialog(html,type){const alreadyOpen=$('#property-dialog').open;if(!alreadyOpen)lastFocus=document.activeElement;dialogView=type;$('#dialog-body').innerHTML=html;if(!alreadyOpen)$('#property-dialog').showModal();$('#property-dialog').scrollTop=0;document.body.style.overflow='hidden';$('#dialog-close').focus()}
  function closeDialog(){$('#property-dialog').close()}
  $('#property-dialog').addEventListener('close',()=>{document.body.style.overflow='';dialogView=null;lastFocus?.focus()});$('#dialog-close').addEventListener('click',closeDialog);$('#property-dialog').addEventListener('click',e=>{const r=e.currentTarget.getBoundingClientRect();if(e.target===e.currentTarget&&(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom))closeDialog()});
  function openProperty(id){const p=properties.find(p=>p.id===id);if(!p)throw new Error('Unknown property');const selected=properties.filter(p=>matchesFilter(p));const index=selected.findIndex(p=>p.id===id);showDialog(`<div class="property-photo"><img id="dialog-photo" class="dialog-photo" src="${p.image}" alt="${p.alt}" loading="eager" style="${p.id==='eagle'?'object-fit:contain':''}"><p class="photo-status" id="dialog-photo-status" role="status" hidden></p></div><div class="dialog-content"><p class="eyebrow">${p.location}</p><h2 id="dialog-title">${state.honest?p.honestTitle:p.title}</h2><p class="dialog-price">${money(p.price)} <small>per month</small></p><p>${state.honest?p.honest:p.detail}</p><div class="dialog-specs">${p.specs.map(x=>`<span>${x}</span>`).join('')}</div><button class="button blue" id="start-viewing">Take a very normal viewing</button><p class="dialog-fine">Al will be present for the key part.</p>${selected.length>1&&index>=0?`<nav class="property-pagination" aria-label="Browse property details"><button id="property-previous">Previous flat</button><span>${index+1} of ${selected.length}</span><button id="property-next">Next flat</button></nav>`:''}</div>`,'property');propertyPhoto($('#dialog-photo'),p,$('#dialog-photo-status'));$('#property-dialog').scrollTop=0;$('#start-viewing').addEventListener('click',()=>{closeDialog();startViewing(id);$('#viewing').scrollIntoView({behavior:state.motion?'smooth':'instant'});$('#viewing-title').setAttribute('tabindex','-1');$('#viewing-title').focus({preventScroll:true})});if(selected.length>1&&index>=0){$('#property-previous').addEventListener('click',()=>openProperty(selected[(index+selected.length-1)%selected.length].id));$('#property-next').addEventListener('click',()=>openProperty(selected[(index+1)%selected.length].id))}return {property:p.id,title:p.title,price:p.price}}
  function startViewing(id){const p=properties.find(p=>p.id===id);if(!p)throw new Error('Unknown property');state.property=id;state.inspected.clear();propertyPhoto($('#viewing-image'),p,$('#viewing-photo-status'));$('#viewing-image').style.objectFit=id==='eagle'?'contain':'cover';$('#viewing-scene').style.background=id==='eagle'?'#84a6ff':'';$('#viewing-property').textContent=p.title;$('#viewing-speech').textContent=p.intro||(id==='studio'?'Welcome to inside the property. You’re doing very well already.':id==='loft'?'Come up. Then slightly down. That’s the ceiling. Welcome.':'Welcome aboard the property. The postcode is currently travelling west.');$$('.hotspot').forEach((b,i)=>{const pos=(p.hotspots||[[25,53],[73,38],[52,79]])[i];b.style.setProperty('--x',pos[0]+'%');b.style.setProperty('--y',pos[1]+'%')});syncInspection();return {property:id,inspected:[]}}
  function syncInspection(){$$('[data-inspect]').forEach(b=>{const yes=state.inspected.has(Number(b.dataset.inspect));b.classList.toggle('checked',yes);b.setAttribute('aria-pressed',String(yes))});$('#viewing-count').textContent=`${state.inspected.size} of 3 things explained away`;$('#viewing-progress').style.width=`${state.inspected.size/3*100}%`;$('#take-flat').textContent=state.inspected.size===3?'I survived. I’ll take it.':'I’ve seen enough. I’ll take it.'}
  function inspect(index){if(!Number.isInteger(index)||index<0||index>2)throw new Error('Inspection index must be 0, 1 or 2');state.inspected.add(index);const p=properties.find(p=>p.id===state.property);$('#viewing-speech').textContent=p.viewing[index];syncInspection();beep(360+index*120,.09);if(state.motion){$('#viewing-scene').classList.remove('bump');void $('#viewing-scene').offsetWidth;$('#viewing-scene').classList.add('bump')}if(state.inspected.size===3)toast('Viewing complete. None of your concerns have been resolved.');document.dispatchEvent(new CustomEvent('eagle:inspect',{detail:{property:p.id,index}}));return {property:p.id,explanation:p.viewing[index],inspected:[...state.inspected]}}
  const answers={
    stath:{intro:'Perfect to meet you. I’m Stath. You can tell from all the Stath things I’ve said.',space:'It’s a very full amount of space. Al went right across it and came back.',pets:'Howley Parker! Have you brought it with you? Carole, there’s a hypothetical dog.',area:'Brand, banking new. The area, I mean. Some of the buildings are very old.',deposit:'I’ve got a key. That’s the first thing to celebrate. We can discuss which key in a bit.'},
    al:{intro:'Hello. Lovely to meet you. Do please let me know if I’m standing where you need to be.',space:'Yes, I can move the chair. It isn’t my chair. I’m very happy to move it, though.',pets:'I’d be delighted to meet them. Professionally, of course. I don’t want to impose on a cat.',area:'It’s very nice. I bought Sophie a little cake here once. I should probably mention the transport.',deposit:'They’re here. I’ve put each one on its own labelled hook. I hope that isn’t presumptuous.'},
    sophie:{intro:'Hello. I’m only here for a bit. Unless the bit turns into the whole day again.',space:'Can I practise something in it? Only it starts quite small and then my arms come out.',pets:'Yes, I like them. Dad likes the quiet ones. I don’t know if that’s the actual rule.',area:'All the fun of the fair. There’s a little shop where I get my crisps.',deposit:'Stath gave me them to hold and then asked why I had all his keys. So I’m just stood here.'},
    carole:{intro:'Hello. Yes, I can show you the property. We can probably do that without an awards ceremony.',space:'Check the dimensions. Stath has measured it in lengths of Al again.',pets:'We’d check with the landlord. That’s the entire process. It doesn’t need a dance.',area:'I can show you the area. Stath has been describing the entire borough as “nearby”.',deposit:'The labelled cupboard. Same place as yesterday. No, the other cupboard. Stath.'},
    cem:{intro:'You’ve come in respectfully. I’ve noticed that straight away. Very good entrance, man.',space:'Whatever space you need, I respect it. I’m leaving a respectful bit here between us.',pets:'If your little dog’s a gentleman, that’s already a strong reference.',area:'Good people. Real gentlemen. You could be the mayor of Gentleman Town around here.',deposit:'Al’s got them. That man has respect absolutely coming off him. I’d trust him with a whole door.'},
    vasos:{intro:'Welcome, welcome. Stath is going to look after you. Al is also here, which is good.',space:'My boy is very good with a room. Al, show him the room as well, please.',pets:'Stathy, come and talk to the customer. Why are we all discussing a bird now?',area:'You come in, you have a look, you find a nice home. Stathy can manage that. Al?',deposit:'My son is doing them. Al, can you do them with my son? Just stand very nearby.'},
    dean:{intro:'Yeah. I’m here. The website has correctly identified that I’m at work.',space:'It’s a studio. There’s one room. I don’t know why that took the others six paragraphs.',pets:'I’ll ask. That’s usually quicker than whatever’s happening over there.',area:'There are places you can go when you finish work. That’s my main interest in it.',deposit:'On the hook. I’m not doing a reveal for a key.'},
    eagle:{intro:'[The eagle has been listed as staff. Nobody has challenged the paperwork.]',space:'[Spreads both wings. Al politely moves a chair.]',pets:'[Looks directly at the “no pets” sign. Slowly removes the sign.]',area:'[Knows the entire area. Will not put this knowledge in an email.]',deposit:'[Produces a key. Then a second key. Then an entire conservatory.]'}
  };
  const staffStatus={stath:'STATH · LETTINGS & INTRODUCTIONS',al:'AL · A VERY GOOD GENTLEMAN',sophie:'SOPHIE · HELPING, APPARENTLY',carole:'CAROLE · PROPERTY DETAILS AVAILABLE',cem:'CEM · RESPECTFULLY PRESENT',vasos:'VASOS · A PROUD FATHER',dean:'DEAN · CURRENTLY AT WORK',eagle:'THE EAGLE · LOCAL COVERAGE'};
  function setAgent(agent){if(!['stath','al','sophie','carole','cem','vasos','dean','eagle'].includes(agent))throw new Error('Unknown office agent');state.agent=agent;state.question=null;$$('[data-agent]').forEach(b=>{const on=b.dataset.agent===agent;b.classList.toggle('selected',on);b.setAttribute('aria-pressed',String(on))});$$('[data-question]').forEach(b=>b.classList.remove('active'));$('#office-reply').textContent=agent==='eagle'?answers[agent].intro:`“${answers[agent].intro}”`;$('#office-status').textContent=staffStatus[agent];document.dispatchEvent(new CustomEvent('eagle:agent',{detail:{agent}}));return {agent}}
  function askOffice(question){if(!['space','pets','area','deposit'].includes(question))throw new Error('Unknown office question');state.question=question;$$('[data-question]').forEach(b=>b.classList.toggle('active',b.dataset.question===question));const answer=answers[state.agent][question];$('#office-reply').textContent=state.agent==='eagle'?answer:`“${answer}”`;beep(480,.08);if(state.agent==='eagle'&&question==='deposit')rain('🔑',12);document.dispatchEvent(new CustomEvent('eagle:answer',{detail:{agent:state.agent,question}}));return {agent:state.agent,question,answer}}
  function setChaos(value){const n=Number(value);if(!Number.isFinite(n)||n<0||n>400)throw new Error('Ambience must be from 0 to 400');state.chaos=Math.round(n);$('#chaos-range').value=state.chaos;$('#chaos-value').value=`${state.chaos}%`;$('#chaos-range').style.setProperty('--range-progress',`${state.chaos/4}%`);const active=n>=60;document.body.classList.toggle('chaos-active',active);document.body.classList.toggle('chaos-extreme',n>=200);document.documentElement.style.setProperty('--chaos-rotation',n<40?'0deg':`${Math.min(2.6,(n-40)/110)}deg`);$('#chaos-toggle').setAttribute('aria-pressed',String(active));$('#chaos-label').textContent=`Office: ${active?'lively':'settled'}`;$('#chaos-description').textContent=n<25?'Everyone has located their lanyard. An excellent start.':n<100?'Someone has microwaved a key. The meeting is delayed.':n<200?'Stath is describing a cupboard as a junior ballroom.':n<350?'All the rooms are doing a movement. The ceiling has joined in.':'Sophie has found the music setting. Stath is very proud of this.';document.dispatchEvent(new CustomEvent('eagle:chaos',{detail:{chaos:state.chaos}}));return {chaos:state.chaos,stathMode:active}}
  function updatePreferences(){document.body.classList.toggle('calm',!state.motion);$('#motion-toggle').setAttribute('aria-pressed',String(state.motion));$('#motion-toggle').textContent=`Motion: ${state.motion?'on':'off'}`;$('#sound-toggle').setAttribute('aria-pressed',String(state.sound));$('#sound-toggle').textContent=`Sound: ${state.sound?'on':'off'}`;if(!state.motion){$('#confetti-layer').replaceChildren();$('#eagle-flight').classList.remove('flying');clearTimeout(flightTimer);flightRunning=false}document.dispatchEvent(new CustomEvent('eagle:preferences'))}
  function stopHold(){held=false;clearInterval(holdTimer);$('#hold-button').textContent='Put me on hold'}
  function hold(){if(held){stopHold();toast('Welcome back. Nothing has been achieved.');return}held=true;$('#hold-button').textContent='Rescue me';toast(state.sound?'Your call is the most important call currently being ignored.':'You are on hold. Switch Sound on below for our tiny hold-music concert.');const notes=[523.25,659.25,783.99,659.25,440,523.25,659.25,0];let n=0;holdTimer=setInterval(()=>{if(n>=32){stopHold();toast('Thank you for holding. We’ve forgotten why you called.');return}if(notes[n%8])beep(notes[n%8],.17,.025);n++},310)}
  function openCupboard(){let tries=new Set();const correct=Math.floor(Math.random()*8);showDialog(`<div class="dialog-content"><p class="eyebrow">STAFF ONLY / NOT EVEN MOST STAFF</p><h2 id="dialog-title">SOMEWHERE<br>IN HERE.</h2><p>One of these opens a flat. The others are a whole administrative situation.</p><div class="key-grid">${Array.from({length:8},(_,i)=>`<button data-key="${i}" aria-label="Try key ${i+1}"><span aria-hidden="true">🔑</span></button>`).join('')}</div><p class="cupboard-result" id="cupboard-result" aria-live="polite">Eight keys. Unlimited confidence. Pick one.</p><p class="dialog-fine">Carole would like these put back in order.</p></div>`,'cupboard');$$('[data-key]').forEach(b=>b.addEventListener('click',()=>{const k=Number(b.dataset.key);if(tries.has(k))return;tries.add(k);if(k===correct){b.classList.add('found');$('#cupboard-result').textContent=`You found it in ${tries.size} ${tries.size===1?'go':'goes'}! You are now Head of Keys. It’s mostly responsibility.`;$$('[data-key]').forEach(b=>b.disabled=true);rain('🔑',24);beep(880,.3);document.dispatchEvent(new CustomEvent('eagle:award',{detail:{id:'key-success',reason:'For locating one correct key among a lifetime of other keys.'}}))}else{b.classList.add('tried');b.disabled=true;const excuses=['That’s for the biscuit tin. Security was getting lax.','That opens a flat we no longer have. Emotionally, we still do.','Bike lock. Nobody has admitted to the bike.','Carole’s emergency drawer. We shouldn’t have tried that.','That’s just a nice key Stath found.','Photocopier key. Don’t ask.','The label says “DO NOT”. Well, now we know.'];$('#cupboard-result').textContent=excuses[(tries.size-1)%excuses.length];beep(200,.12);document.dispatchEvent(new CustomEvent('eagle:award',{detail:{id:'wrong-key',reason:'For trying a key with enormous personal confidence.'}}))}}))}
  $$('[data-filter]').forEach(b=>b.addEventListener('click',()=>setFilter(b.dataset.filter)));
  $('#translator').addEventListener('click',()=>{setTranslation(!state.honest);beep(state.honest?620:400,.12)});
  $('#lottery-button').addEventListener('click',()=>{const visible=properties.filter(p=>matchesFilter(p));const p=visible[Math.floor(Math.random()*visible.length)];if(p)openProperty(p.id);beep(600,.15)});
  $$('[data-inspect]').forEach(b=>b.addEventListener('click',()=>inspect(Number(b.dataset.inspect))));$('#viewing-reset').addEventListener('click',()=>startViewing(state.property));
  $('#take-flat').addEventListener('click',()=>{if(state.inspected.size<3)document.dispatchEvent(new CustomEvent('eagle:award',{detail:{id:'early-yes',reason:'For saying yes before anyone had finished explaining the ceiling.'}}));const p=properties.find(p=>p.id===state.property);showDialog(`<div class="dialog-content"><p class="eyebrow">A VERY BIG DAY FOR INSIDE</p><div class="big-congratulations" aria-hidden="true">🔑</div><h2 id="dialog-title">YOU’VE GOT<br>AN INSIDE.</h2><p>Congratulations. ${p.title}. An excellent choosing. Stath is already looking for the keys.</p><p class="dialog-fine">Al has gone to find a second set, which is sensible of Al.</p><button class="button blue" id="success-close">A very sensible decision</button></div>`,'success');$('#success-close').addEventListener('click',closeDialog);rain('🔑',32);beep(784,.25);setTimeout(()=>beep(1047,.3),220)});
  $$('[data-agent]').forEach(b=>b.addEventListener('click',()=>setAgent(b.dataset.agent)));$$('[data-question]').forEach(b=>b.addEventListener('click',()=>askOffice(b.dataset.question)));
  $('#chaos-range').addEventListener('input',e=>setChaos(e.target.value));$('#chaos-range').addEventListener('change',()=>{if(state.chaos>=300)document.dispatchEvent(new CustomEvent('eagle:crump',{detail:{kind:'crump'}}))});$('#chaos-toggle').addEventListener('click',()=>{setChaos(state.chaos>=60?20:400);if(state.chaos>=60){document.dispatchEvent(new CustomEvent('eagle:crump',{detail:{kind:'crump'}}))}});
  $('#motion-toggle').addEventListener('click',()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches){state.motion=false;toast('Reduced motion is enabled on your device. Keeping things steady.')}else state.motion=!state.motion;updatePreferences()});$('#sound-toggle').addEventListener('click',()=>{state.sound=!state.sound;updatePreferences();if(state.sound){beep(640,.15);toast('Sound on. The office is now slightly audible.')}else toast('Sound off. A very reasonable request.')});
  $('#hold-button').addEventListener('click',hold);$('#staff-door').addEventListener('click',openCupboard);$('#key-button').addEventListener('click',()=>{rain('🔑',28);toast('Oh my gilly goodness. Those are everybody’s keys.');document.dispatchEvent(new CustomEvent('eagle:award',{detail:{id:'all-keys',reason:'For requesting one key and receiving the whole agency.'}}));beep(900,.13)});$('#eagle-button').addEventListener('click',unleashEagle);$('#one-more-eagle').addEventListener('click',openCoverage);$('#back-top').addEventListener('click',()=>window.scrollTo({top:0,behavior:state.motion?'smooth':'instant'}));
  document.addEventListener('visibilitychange',()=>{if(document.hidden)stopHold()});matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',e=>{state.motion=!e.matches;updatePreferences()});
  renderCards();updatePreferences();setChaos(80);syncInspection();propertyPhoto($('#viewing-image'),properties[0],$('#viewing-photo-status'));
  window.eaglePlayground={getSettings:()=>({motion:state.motion,sound:state.sound,chaos:state.chaos,property:state.property,agent:state.agent}),setChaos,rain,toast,unleashEagle,nextEagleQuip,beep,withAudio,setAgent,setTranslation,showDialog,closeDialog,openCupboard,toggleSound:()=>$('#sound-toggle').click(),restoreOrder:()=>{clearTimeout(flightTimer);flightRunning=false;$('#eagle-flight').classList.remove('flying');$('#confetti-layer').replaceChildren();stopHold();setChaos(0)}};

  const modelContext=document.modelContext;
  if(modelContext?.registerTool){const lifecycle=new AbortController();const tools=[{name:'filter_imaginary_flats',title:'Filter imaginary flats',description:'Change the visible fictional property filter. Does not book or contact anyone.',inputSchema:{type:'object',properties:{filter:{type:'string',enum:['all','new','budget','airborne']}},required:['filter'],additionalProperties:false},execute:input=>setFilter(input.filter)},{name:'translate_property_descriptions',title:'Translate agent-speak',description:'Toggle the humorous honest descriptions on the visible property cards.',inputSchema:{type:'object',properties:{enabled:{type:'boolean'}},required:['enabled'],additionalProperties:false},execute:input=>setTranslation(input.enabled)},{name:'ask_fictional_office',title:'Ask the fictional office',description:'Select an agent and display a scripted humorous answer. No real person is contacted.',inputSchema:{type:'object',properties:{agent:{type:'string',enum:['stath','al','sophie','carole','cem','vasos','dean','eagle']},question:{type:'string',enum:['space','pets','area','deposit']}},required:['agent','question'],additionalProperties:false},execute:input=>{if(!['stath','al','sophie','carole','cem','vasos','dean','eagle'].includes(input.agent)||!['space','pets','area','deposit'].includes(input.question))throw new Error('Invalid office choice');setAgent(input.agent);return askOffice(input.question)}}];for(const t of tools){try{Promise.resolve(modelContext.registerTool({...t,annotations:{readOnlyHint:false,untrustedContentHint:false}}, {signal:lifecycle.signal})).catch(()=>{})}catch{}}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true})}
})();
