'use strict';
(() => {
  const api=window.eaglePlayground;
  if(!api)return;
  const $=s=>document.querySelector(s);
  const $$=s=>[...document.querySelectorAll(s)];
  const stage=$('#crump-stage');
  const timers=new Set(),animations=new Set(),nodes=new Set();
  const kinds=['crump','eagles','paperwork','shuffle'];
  let playing=null,session=0,roomTimer=null,resumeChaos=null;
  const statuses={crump:'Al, I think we’ve left the music on this bit.',eagles:'Howley Parker! That’s quite a wide area.',paperwork:'That’s all the company literature. It’s come out at once.',shuffle:'All the fun of the fair. Is this the floor plan, Al?'};
  function schedule(fn,ms){const current=session;const id=setTimeout(()=>{timers.delete(id);if(current===session)fn()},ms);timers.add(id);return id}
  function moving(){return api.getSettings().motion&&!document.hidden}
  function animate(element,frames,options){if(!moving()||!element?.animate)return null;const a=element.animate(frames,{...options,fill:'none'});animations.add(a);a.onfinish=()=>animations.delete(a);a.oncancel=()=>animations.delete(a);return a}
  function stopAudio(){for(const n of nodes){try{n.stop()}catch{}}nodes.clear()}
  function hit(kind,n=0){if(!api.getSettings().sound||document.hidden)return;const current=session;api.withAudio(audioContext=>{if(current!==session)return;try{const t=audioContext.currentTime;const gain=audioContext.createGain();gain.connect(audioContext.destination);let source,duration;
      if(kind==='kick'){source=audioContext.createOscillator();source.type='sine';source.frequency.setValueAtTime(180,t);source.frequency.exponentialRampToValueAtTime(58,t+.18);gain.gain.setValueAtTime(.14,t);duration=.22}
      else if(kind==='bass'){source=audioContext.createOscillator();source.type='triangle';source.frequency.value=[130.81,130.81,155.56,116.54][n%4];gain.gain.setValueAtTime(.065,t);duration=.2}
      else{duration=kind==='hat'?.045:.13;const buffer=audioContext.createBuffer(1,Math.ceil(audioContext.sampleRate*duration),audioContext.sampleRate);const data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*(1-i/data.length);source=audioContext.createBufferSource();source.buffer=buffer;gain.gain.setValueAtTime(kind==='hat'?.025:.05,t)}
      gain.gain.exponentialRampToValueAtTime(.0001,t+duration);source.connect(gain);source.start(t);source.stop(t+duration+.01);nodes.add(source);source.onended=()=>{nodes.delete(source);source.disconnect();gain.disconnect()};
    }catch{stopAudio()}})}

  function rhythm(){for(let i=1;i<64;i++){schedule(()=>{if(i%4===0)hit('kick');if(i%8===4)hit('snare');if(i%2===0)hit('hat');if(i%4===2)hit('bass',Math.floor(i/8))},i*117)}}
  function word(text){if(!moving())return;const el=document.createElement('div');el.className='crump-word';el.textContent=text;stage.append(el);schedule(()=>el.remove(),1380)}
  function dance(power=1){if(!moving())return;const targets=$$('.hero-copy h1,.hero-art,.property-card,.office-board,.viewing-scene,.crump-pad,.office-stamp,.crump-intro h2').filter(el=>{const r=el.getBoundingClientRect();return r.bottom>0&&r.top<innerHeight&&!el.hidden});targets.forEach((el,i)=>{const sign=i%2?-1:1;animate(el,[{transform:'translate(0,0) rotate(0)'},{transform:`translate(${sign*7*power}px,${-14*power}px) rotate(${sign*5*power}deg)`,offset:.23},{transform:`translate(${-sign*5*power}px,${5*power}px) rotate(${-sign*4*power}deg)`,offset:.5},{transform:`translate(${sign*2*power}px,${-5*power}px) rotate(${sign*2*power}deg)`,offset:.72},{transform:'translate(0,0) rotate(0)'}],{duration:840,easing:'cubic-bezier(.3,.8,.4,1)',delay:i*35})})}
  function eagle(i){if(!moving())return;if(api.nextEagleQuip)api.toast(api.nextEagleQuip());const img=document.createElement('img');img.className='crump-eagle';img.src='assets/eagle.webp';img.alt='';const reverse=i%2;img.style.top=`${8+(i*19)%62}%`;img.style.left='0';stage.append(img);const start=reverse?'110vw':'-100%';const finish=reverse?'-100%':'110vw';const a=animate(img,[{transform:`translateX(${start}) rotate(${reverse?16:-16}deg) scale(.8)`},{transform:`translateX(${reverse?'42vw':'22vw'}) rotate(${reverse?-9:9}deg) scale(1)`,offset:.5},{transform:`translateX(${finish}) rotate(${reverse?14:-14}deg) scale(.8)`}],{duration:2800,easing:'ease-in-out'});if(a)a.onfinish=()=>{animations.delete(a);img.remove()};schedule(()=>img.remove(),2900)}
  function memo(i){if(!moving())return;const papers=[['FLAT TOO FLAT','Please add a bit of height.'],['KEYS: LOST AGAIN','Have you checked the key area?'],['CEILING MEETING','Attendance from above.'],['VERY NICE SMELL','We have opened a window.'],['BIRD EXPENSES','One whole house. No receipt.'],['CAROLE SAID NO','This form is now complete.']];const [title,body]=papers[i%papers.length];const el=document.createElement('div');el.className='crump-memo';const small=document.createElement('small'),b=document.createElement('b'),span=document.createElement('span');small.textContent='M&E / IMPORTANT LITTLE PAPER';b.textContent=title;span.textContent=body;el.append(small,b,span);el.style.left=`${8+(i*23)%65}%`;el.style.top='0';stage.append(el);const angle=(i%2?1:-1)*(8+(i%3)*7);const a=animate(el,[{transform:`translateY(-220px) rotate(${angle-40}deg)`,opacity:0},{transform:`translateY(${20+(i*13)%35}vh) rotate(${angle}deg)`,opacity:1,offset:.35},{transform:`translateY(${25+(i*13)%35}vh) rotate(${-angle}deg)`,opacity:1,offset:.72},{transform:`translateY(110vh) rotate(${angle+65}deg)`,opacity:0}],{duration:2700,easing:'ease-in-out'});if(a)a.onfinish=()=>{animations.delete(a);el.remove()};schedule(()=>el.remove(),2800)}
  function tag(i){if(!moving())return;const el=document.createElement('div');el.className='crump-label';el.textContent=['PERFECT TO MEET YOU.','ALL THE FUN OF THE FAIR.','HOWLEY PARKER!','A VERY NICE FLOOR.','BRAND, BANKING NEW.'][i%5];el.style.left=`${7+(i*17)%62}%`;el.style.top=`${15+(i*21)%60}%`;stage.append(el);const a=animate(el,[{transform:'scale(.2) rotate(-22deg)',opacity:0},{transform:`scale(1.15) rotate(${i%2?12:-12}deg)`,opacity:1,offset:.3},{transform:`scale(.95) rotate(${i%2?-7:7}deg)`,opacity:1,offset:.7},{transform:'scale(.5) translateY(180px) rotate(35deg)',opacity:0}],{duration:1800,easing:'cubic-bezier(.2,.8,.3,1)'});if(a)a.onfinish=()=>{animations.delete(a);el.remove()};schedule(()=>el.remove(),1900)}
  function updateSound(){const sound=api.getSettings().sound;$('#crump-sound').setAttribute('aria-pressed',String(sound));$('#crump-sound').textContent=sound?'Sound: on':'Sound: off';if(!sound)stopAudio()}
  function stop({rescue=false,quiet=false}={}){session++;for(const t of timers)clearTimeout(t);timers.clear();for(const a of [...animations])a.cancel();animations.clear();stopAudio();clearTimeout(roomTimer);$('#viewing-scene').classList.remove('room-disco');stage.replaceChildren();$$('.crump-overlay').forEach(el=>el.remove());document.body.classList.remove('crump-running');$$('[data-crump]').forEach(b=>b.setAttribute('aria-pressed','false'));$('#crump-stop').hidden=true;playing=null;const previous=resumeChaos;resumeChaos=null;if(!rescue&&previous!==null)api.setChaos(previous);if(rescue){api.restoreOrder();$('#crump-status').textContent='Carole has put the presentation back in order.';if(!quiet)api.toast('Carole has restored order. Nobody is allowed a tambourine.')}else if(!quiet)$('#crump-status').textContent='Thank you. That should have been the property details.';return {playing:false}}
  function play(kind='crump'){if(!kinds.includes(kind))throw new Error('Unknown crump performance');stop({quiet:true});resumeChaos=api.getSettings().chaos;playing=kind;api.setChaos(400);document.body.classList.add('crump-running');$$('[data-crump]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.crump===kind)));$('#crump-stop').hidden=false;$('#crump-status').textContent=statuses[kind];api.toast(statuses[kind]);hit('kick');rhythm();if(!moving()){$('#crump-status').textContent=statuses[kind]+' The office is keeping still, as requested.';schedule(()=>stop(),8000);return {playing:true,kind,motion:false}}
    const overlay=document.createElement('div');overlay.className='crump-overlay';document.body.append(overlay);for(let beat=0;beat<8;beat++)schedule(()=>dance(beat%2?.85:1.15),beat*936);
    if(kind==='crump'){word('HOWLEY PARKER!');schedule(()=>api.rain('🔑',30),350);schedule(()=>eagle(0),1400);schedule(()=>memo(0),2800);schedule(()=>memo(1),3250);schedule(()=>word('ALL THE FUN OF THE FAIR.'),4250);schedule(()=>eagle(1),4600);schedule(()=>tag(3),6100);schedule(()=>word('RESPECT. ABSOLUTELY.'),6550)}
    else if(kind==='eagles'){word('OUR LOCAL EXPERTISE.');for(let i=0;i<6;i++)schedule(()=>eagle(i),500+i*860);schedule(()=>word('HOWLEY PARKER!'),4900)}
    else if(kind==='paperwork'){word('COMPANY LITERATURE.');for(let i=0;i<9;i++)schedule(()=>memo(i),400+i*530);schedule(()=>word('SILLY BILLY AWARDS.'),6100)}
    else{word('ALL THE FUN OF THE FAIR.');for(let i=0;i<8;i++)schedule(()=>tag(i),600+i*760);schedule(()=>api.rain('✳',32),2800);schedule(()=>word('THAT’S A VERY NICE FLOOR.'),5100)}
    schedule(()=>stop(),8250);return {playing:true,kind,motion:true}}
  $$('[data-crump]').forEach(b=>b.addEventListener('click',()=>play(b.dataset.crump)));
  $('#carole-rescue').addEventListener('click',()=>{stop({rescue:true});document.dispatchEvent(new CustomEvent('eagle:restore'))});$('#crump-stop').addEventListener('click',()=>{stop({rescue:true});document.dispatchEvent(new CustomEvent('eagle:restore'))});$('#crump-sound').addEventListener('click',()=>{api.toggleSound();updateSound();if(api.getSettings().sound&&!playing){hit('kick');api.beep(523,.1)}});
  document.addEventListener('eagle:preferences',()=>{updateSound();if(!api.getSettings().motion)stop({quiet:true})});
  document.addEventListener('eagle:chaos',e=>{const value=e.detail.chaos;$('.crump-readout b').textContent=value>=300?'REVISED':'READY';if(value<60&&playing)stop({quiet:true})});
  document.addEventListener('eagle:crump',e=>play(e.detail?.kind||'crump'));
  document.addEventListener('eagle:inspect',e=>{if(e.detail.index===1&&e.detail.property==='studio'){clearTimeout(roomTimer);if(moving())$('#viewing-scene').classList.add('room-disco');api.toast('The disco ball is part of the fixtures and feelings.');hit('kick');roomTimer=setTimeout(()=>$('#viewing-scene').classList.remove('room-disco'),4200)}else if(moving()){const img=$('#viewing-image');animate(img,[{transform:'scale(1.05) rotate(0)'},{transform:'scale(1.12) rotate(4deg)'},{transform:'scale(1.07) rotate(-3deg)'},{transform:'scale(1) rotate(0)'}],{duration:1050,easing:'ease-in-out'})}});
  $$('.wobble-word').forEach((wordEl,wordIndex)=>{const original=wordEl.textContent;wordEl.setAttribute('role','button');wordEl.setAttribute('tabindex','0');wordEl.setAttribute('aria-label',`${original} — company heading`);function wobble(){if(!moving()){api.toast(['The words have developed professional enthusiasm.','You are very much in the wording.','It’s got a roof over the letters.'][wordIndex]);return}wordEl.replaceChildren();for(const char of original){const span=document.createElement('span');span.className='hero-letter';span.textContent=char;span.setAttribute('aria-hidden','true');wordEl.append(span)}[...wordEl.children].forEach((letter,i)=>{animate(letter,[{transform:'translate(0,0) rotate(0)'},{transform:`translate(${(i%3-1)*7}px,${-25-i%3*12}px) rotate(${i%2?19:-19}deg)`,offset:.28},{transform:`translate(0,9px) rotate(${i%2?-8:8}deg)`,offset:.64},{transform:'translate(0,0) rotate(0)'}],{duration:850,delay:i*48,easing:'cubic-bezier(.2,.8,.3,1)'})});hit('kick');api.toast(['Those words were load-bearing.','You’ve put some movement in the sentence.','That’s a very lively bit of property.'][wordIndex])}wordEl.addEventListener('click',wobble);wordEl.addEventListener('keydown',e=>{if(e.key===' '||e.key==='Enter'){e.preventDefault();wobble()}})});
  document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(playing)stop({rescue:true});return}if(e.ctrlKey||e.metaKey||e.altKey||e.repeat||e.target.closest?.('input,textarea,select,[contenteditable="true"]')||$('#property-dialog').open)return;if(e.key.toLowerCase()==='c'&&e.shiftKey)play('crump')});
  document.addEventListener('visibilitychange',()=>{if(document.hidden)stop({quiet:true})});
  window.addEventListener('pagehide',()=>stop({quiet:true}));
  updateSound();
  window.eagleCrump={play,stop,getState:()=>({playing,scheduled:timers.size,animations:animations.size,audioNodes:nodes.size})};
})();
